# Generated by Django 4.2.2 on 2023-06-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf_funcionario', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome_funcionario', models.TextField()),
                ('cargo', models.CharField(max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_estoque', models.IntegerField()),
                ('descricao', models.TextField()),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('senha', models.TextField()),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('cpf_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('setor', models.TextField(primary_key=True, serialize=False)),
                ('corredor', models.IntegerField()),
                ('pratileira', models.IntegerField()),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.produto')),
            ],
        ),
    ]
