# Generated by Django 4.2.2 on 2023-06-25 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_produto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVendas',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('cpf_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.usuario')),
            ],
        ),
    ]
