# Generated by Django 4.2.2 on 2023-06-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_registrovendas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrovendas',
            old_name='id_produto',
            new_name='id_venda',
        ),
    ]
