# Generated by Django 4.2.2 on 2023-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_folhaponto_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhaponto',
            name='data_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='folhaponto',
            name='data_saida',
            field=models.DateTimeField(),
        ),
    ]
