# Generated by Django 4.2.2 on 2023-06-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_folhaponto_data_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrovendas',
            old_name='cpf_usuario',
            new_name='cpf',
        ),
    ]
