# Generated by Django 4.2.2 on 2023-06-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_cpf_usuario_registrovendas_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrovendas',
            old_name='cpf',
            new_name='cpf_usuario',
        ),
    ]
