# Generated by Django 4.2.2 on 2023-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_cpf_registrovendas_cpf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovendas',
            name='quantidade',
            field=models.TextField(),
        ),
    ]
