# Generated by Django 4.2.2 on 2023-06-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_funcionario_senha_func_funcionario_tipo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='senha_func',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_acesso',
            field=models.TextField(),
        ),
    ]
