# Generated by Django 4.2.2 on 2023-06-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_funcionario_senha_func_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.TextField()),
                ('quantidade', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('cpf_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.usuario')),
            ],
        ),
    ]
