# Generated by Django 4.2.2 on 2023-06-28 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_registrocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocompra',
            name='cpf_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.funcionario'),
        ),
    ]
