# Generated by Django 4.2.2 on 2023-06-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_registrocompra_cpf_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhaponto',
            name='data_entrada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='folhaponto',
            name='data_saida',
            field=models.TextField(),
        ),
    ]
