# Generated by Django 4.2.2 on 2023-06-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_folhaponto_data_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='pratileira',
            new_name='prateleira',
        ),
    ]
